# Generated by Django 2.0.8 on 2018-09-03 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pn', models.IntegerField()),
                ('Date', models.DateField()),
                ('Qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Masterdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material', models.IntegerField()),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('TypeDescription', models.CharField(blank=True, max_length=50, null=True)),
                ('Segmentation', models.CharField(blank=True, max_length=5, null=True)),
                ('Hierarchy', models.CharField(blank=True, max_length=20, null=True)),
                ('Type', models.CharField(blank=True, max_length=5, null=True)),
                ('SupplyPlant', models.IntegerField(blank=True, null=True)),
                ('SS0015', models.IntegerField(blank=True, null=True)),
                ('Outlier0015', models.IntegerField(blank=True, null=True)),
                ('SS0360', models.IntegerField(blank=True, null=True)),
                ('Outier0360', models.IntegerField(blank=True, null=True)),
                ('Con0015', models.IntegerField(blank=True, null=True)),
                ('Con0360', models.IntegerField(blank=True, null=True)),
                ('Vendor', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pn', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ymon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=20, null=True)),
                ('U', models.CharField(blank=True, max_length=1, null=True)),
                ('Sold_To_Party', models.IntegerField(blank=True, null=True)),
                ('Name_1', models.CharField(blank=True, max_length=30, null=True)),
                ('Sales_Document', models.CharField(blank=True, max_length=10, null=True)),
                ('Item', models.CharField(blank=True, max_length=2, null=True)),
                ('Purchase_order_no', models.CharField(blank=True, max_length=10, null=True)),
                ('Material', models.CharField(blank=True, max_length=10, null=True)),
                ('MRP_Type', models.CharField(blank=True, max_length=2, null=True)),
                ('Description', models.CharField(blank=True, max_length=30, null=True)),
                ('Ident_code_1', models.CharField(blank=True, max_length=30, null=True)),
                ('Ident_code_2', models.CharField(blank=True, max_length=30, null=True)),
                ('Order_Quantity', models.IntegerField(blank=True, null=True)),
                ('Open_quantity', models.IntegerField(blank=True, null=True)),
                ('Pos_created_on', models.DateField(blank=True, null=True)),
                ('Actconf_date', models.DateField(blank=True, null=True)),
                ('Requested_deliv_date', models.DateField(blank=True, null=True)),
                ('Delta', models.IntegerField(blank=True, null=True)),
                ('LT', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
