# Generated by Django 2.0.8 on 2018-09-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=20)),
                ('SGFCode', models.CharField(max_length=20)),
                ('Focus', models.CharField(max_length=20)),
                ('Pn', models.CharField(max_length=20)),
            ],
        ),
    ]
