# Generated by Django 2.0.8 on 2018-08-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ymon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=20, null=True)),
                ('U', models.CharField(blank=True, max_length=1, null=True)),
                ('Sold_To_Party', models.IntegerField(blank=True, null=True)),
                ('Name_1', models.CharField(blank=True, max_length=30, null=True)),
                ('Sales_Document', models.CharField(blank=True, max_length=10, null=True)),
                ('Item', models.CharField(blank=True, max_length=2, null=True)),
                ('Purchase_order_no', models.CharField(blank=True, max_length=10, null=True)),
                ('Material', models.CharField(blank=True, max_length=10, null=True)),
                ('MRP_Type', models.CharField(blank=True, max_length=2, null=True)),
                ('Description', models.CharField(blank=True, max_length=30, null=True)),
                ('Ident_code_1', models.CharField(blank=True, max_length=30, null=True)),
                ('Ident_code_2', models.CharField(blank=True, max_length=30, null=True)),
                ('Order_Quantity', models.IntegerField(blank=True, null=True)),
                ('Open_quantity', models.IntegerField(blank=True, null=True)),
                ('Pos_created_on', models.DateField(blank=True, null=True)),
                ('Actconf_date', models.DateField(blank=True, null=True)),
                ('Requested_deliv_date', models.DateField(blank=True, null=True)),
                ('Delta', models.IntegerField(blank=True, null=True)),
                ('LT', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
