# Generated by Django 2.0.8 on 2018-09-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0002_productfamily'),
    ]

    operations = [
        migrations.CreateModel(
            name='YCP4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pn', models.CharField(max_length=10)),
                ('Description', models.CharField(blank=True, max_length=30, null=True)),
                ('Con3M', models.IntegerField()),
                ('Con12M', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('Incoming', models.IntegerField()),
                ('Order', models.IntegerField()),
            ],
        ),
    ]
