# Generated by Django 2.0.8 on 2018-09-03 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0003_ycp4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ycp4',
            old_name='Pn',
            new_name='Masterial',
        ),
    ]
