# Generated by Django 2.0.8 on 2018-09-03 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0004_auto_20180904_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='ymon',
            name='ycp4',
            field=models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, to='loteam.YCP4'),
        ),
    ]
