# Generated by Django 2.0.8 on 2018-09-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0006_auto_20180904_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ycp4',
            old_name='Masterial',
            new_name='Material',
        ),
    ]
