# Generated by Django 2.0.8 on 2018-09-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0007_auto_20180904_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ymon',
            old_name='Material',
            new_name='ycp4',
        ),
    ]
