# Generated by Django 2.0.8 on 2018-09-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0009_auto_20180904_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ycp4',
            name='Material',
            field=models.IntegerField(),
        ),
    ]
