# Generated by Django 2.0.8 on 2018-09-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0012_auto_20180904_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
