# Generated by Django 2.0.8 on 2018-09-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0013_auto_20180904_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material', models.IntegerField()),
            ],
        ),
    ]
