# Generated by Django 2.0.8 on 2018-09-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0014_clearing'),
    ]

    operations = [
        migrations.AddField(
            model_name='ymon',
            name='Remark',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ymon',
            name='Topticket',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
