# Generated by Django 2.0.8 on 2018-09-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0015_auto_20180904_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='ymon',
            name='Shippingcondition',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
