# Generated by Django 2.0.8 on 2018-09-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0016_ymon_shippingcondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ycp4',
            name='id',
        ),
        migrations.AlterField(
            model_name='ycp4',
            name='Material',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
