# Generated by Django 2.0.8 on 2018-09-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0017_auto_20180907_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ycp4',
            name='Con12M',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ycp4',
            name='Con3M',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ycp4',
            name='Incoming',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ycp4',
            name='Order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ycp4',
            name='Stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
