# Generated by Django 2.0.8 on 2018-09-10 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0019_auto_20180910_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdata',
            name='ProductFamily',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='loteam.ProductFamily'),
        ),
    ]
