# Generated by Django 2.0.8 on 2018-09-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0020_masterdata_productfamily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterdata',
            name='ProductFamily',
        ),
    ]
