# Generated by Django 2.0.8 on 2018-09-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0021_remove_masterdata_productfamily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ymon',
            name='Category',
        ),
    ]
