# Generated by Django 2.0.8 on 2018-09-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0022_remove_ymon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ycp4',
            name='Status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
