# Generated by Django 2.0.8 on 2018-09-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteam', '0023_ycp4_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ycp4',
            name='Mrp',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
