# Generated by Django 2.0.8 on 2018-10-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('SA_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.CharField(blank=True, max_length=30, null=True)),
                ('Number_of_suppliers', models.CharField(blank=True, max_length=30, null=True)),
                ('Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Details_1', models.CharField(blank=True, max_length=50, null=True)),
                ('Details_2', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('Updated_date', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier1', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier1_Fabricating_Goods', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier1_Modification_of_free_offerd_item', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier1_Qty', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier1_Final_Unit_Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier2', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier2_Fabricating_Goods', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier2_Modification_of_free_offerd_item', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier2_Qty', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier2_Final_Unit_Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier3', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier3_Fabricating_Goods', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier3_Modification_of_free_offerd_item', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier3_Qty', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier3_Final_Unit_Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier4', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier4_Fabricating_Goods', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier4_Modification_of_free_offerd_item', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier4_Qty', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier4_Final_Unit_Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier5', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier5_Fabricating_Goods', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier5_Modification_of_free_offerd_item', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier5_Qty', models.CharField(blank=True, max_length=50, null=True)),
                ('Supplier5_Final_Unit_Price', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
