# Generated by Django 2.0.8 on 2018-10-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='Supplier6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assay',
            name='Supplier6_Fabricating_Goods',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assay',
            name='Supplier6_Final_Unit_Price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assay',
            name='Supplier6_Modification_of_free_offerd_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assay',
            name='Supplier6_Qty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
