# Generated by Django 2.0.8 on 2018-11-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_auto_20181023_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('SA_No', models.IntegerField(primary_key=True, serialize=False)),
                ('DateTime', models.DateTimeField(primary_key=True)),
                ('User', models.CharField(max_length=30, primary_key=True)),
                ('Field', models.CharField(max_length=30, primary_key=True)),
                ('Before', models.CharField(blank=True, max_length=50, null=True)),
                ('After', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
