# Generated by Django 2.0.8 on 2018-11-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changelog',
            name='DateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='Field',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='SA_No',
            field=models.IntegerField(blank=True, default=99999999, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='User',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='changelog',
            unique_together={('SA_No', 'DateTime', 'User', 'Field')},
        ),
    ]
