# Generated by Django 2.0.8 on 2018-11-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_auto_20181115_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='SA_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='changelog',
            unique_together=set(),
        ),
    ]
