# Generated by Django 2.0.8 on 2018-11-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_auto_20181115_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeLog',
        ),
    ]
