# Generated by Django 2.0.8 on 2018-11-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_changelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='Id',
        ),
        migrations.AlterField(
            model_name='changelog',
            name='SA_No',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
