# Generated by Django 2.0.8 on 2018-11-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0008_auto_20181115_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeLog',
        ),
    ]
