# Generated by Django 2.0.8 on 2018-11-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_auto_20181119_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='DateTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
