# Generated by Django 2.0.8 on 2018-11-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_remove_assay_changedocoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='assay',
            name='Category',
            field=models.CharField(default='신규등록', max_length=50),
        ),
    ]
